# Generated by Django 4.2 on 2023-04-10 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'permissions': (('change_name', 'can change name of product'),)},
        ),
    ]
