# Generated by Django 4.2 on 2023-04-10 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_myuser_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='is_active',
        ),
    ]
